### ISSUE TITLE
if infraappium is installed on Ubuntu 18.04 then libc6 of 2.29 version is needed over 2.23

### ISSUE THREAD

**Issue by yashaka** [zebrunner/android-device#11]
There is an error on Ubuntu 18.04 based infraappium, when appium tries to install and sign apk (inside appium-device container):

dpkg: error processing package libc6:i386 (--install):
 package libc6:i386 2.29-0ubuntu2 cannot be configured because libc6:amd64 is at a different version (2.23-0ubuntu11)

It can be fixed by upgrading libc6 to 2.29...

**Comment by yashaka** [comment]
The workaround I have found is implemented here: https://github.com/yashaka/appium-device/commit/13dde84e9e21551a4d2bfe928c550ba5506a691a

I am adding the "switching to the 2.29 version at the end of Dockerfile.

Actually... It really seems like a workaround, because installing libc6 2.29 earlier will break another needed packages to be build or installed... 

That's why I have not created a PR... I don't know how to implement proper fix so far...

**Comment by vdelendik** [comment]
fixed in upcoming android-device image
