### ISSUE TITLE
configgen or startup should be parametrized to reuse any version of Appium

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/android-device#12]
details: https://github.com/qaprosoft/infrappium/issues/51

**Comment by vdelendik** [comment]
goal of the ticket: 
before the startup of the udev rules registration download required version of appium from public s3 storage and add as docker-volume with valid credentials for user 1000:1000

**Comment by vdelendik** [comment]
issue is solved by using absolutely different approach

**Comment by dhreben** [comment]
Ticket closed
Won't fix.
