### ISSUE TITLE
register vncLink as custom capability for each android device

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/android-device#28]
we use websockey to organize remote vnc access to device...
in scope of the ticket let' register new property: vncLink.
it should be organized in a little bit different way and already contains:
1) valid protocol (ws or wss) 
2) public hostname of the stf
3) relative mcloud/appium url to private host port

i.e. something like this
ws://hostname/mcloud/vnc/private_host/port

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/android-device/commit/c15505378ad28009e53a2ec4f5eae8af4f69078d

**Comment by dhreben** [comment]
**Test scenario:**

1.Open Jenkins
2.Run RegisterRepository
3.Run RegisterHubCredentials 
 - use name repo
 - mcloud
 - http://hostname:port/wd/hub
 
4.Run Mobile-Android-Demo-Test
5.Open Reporting
6.Check that VNC in progress can  be able to click on device

**Actual result:** There is VNC black screen  in progress

<img width="956" alt="Screenshot 2021-01-21 at 20 17 02" src="https://user-images.githubusercontent.com/50950954/105386597-a19e8d00-5c25-11eb-90a8-4b9ab433c52f.png">

**Comment by vdelendik** [comment]
1. websockify from master is too sensitive to external python env (we use it to build it during docker image creation).
-> to fix it we have to checkout into the v0.9.0 release tag (it will be ported to current 1.0 release)
2. complex redirection via ngix usin mcloud location rule fails due to the 405 method not allowed
-> this particular issue should be fixed on reporting side I believe (TBD)
3. All kind of changes are too risky so we have to return old approach when client browser should have direct access to the android slave server
-> vncLink argument should be updated to: protocol://host:port
for the next release we have to investigate howto organize websocket/vnc connection w/o direct access to slave node host with android devices

So changed milestone accordinly

**Comment by dhreben** [comment]
Fixed.

**Comment by vdelendik** [comment]
improved to support distributed setup as well:
https://github.com/zebrunner/android-device/pull/55
