### ISSUE TITLE
made automationName=uiautomator2 as default

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/android-device#33]
change logic and specify for Android versions 4-6
AUTOMATION_NAME='Appium'

And by default use uiautomator2 so we can support new versions without regenerating container

**Comment by vdelendik** [comment]
done. to test:
1. Setup zebrunner from develop branch with mcloud enabled.
2. Configure mcloud-android having Android 6 and Android 7+.
3. Analyze "Configuration" details in http://hostname/mcloud/grid/console
-> For Android v7 and higher automationName should be uiautomator2
![image](https://user-images.githubusercontent.com/4551455/104845662-a1ca2000-58e7-11eb-9128-a61121275065.png)
-> For Android v4-6 there should be registered 'Appium'
4. Run Mobile-Android-Demo-Test on both devices
-> tests should be started, actions executed

**Comment by dhreben** [comment]
**Case 1:**

1.Android v7 and higher automationName  made automationName=uiautomator2 as default

<img width="553" alt="Screenshot 2021-01-21 at 00 47 00" src="https://user-images.githubusercontent.com/50950954/105244911-394a9f80-5b82-11eb-856a-b9683a822f77.png">

2.Mobile-Android-Demo-Test  runned and produced screenshot/video artifacts.

<img width="771" alt="Screenshot 2021-01-21 at 01 05 51" src="https://user-images.githubusercontent.com/50950954/105246808-d1e21f00-5b84-11eb-9cae-c7a8c9b03c0c.png">


**Case 2:** 

Can't find a working device with android 4-6 version
