### ISSUE TITLE
syncup zebrunner and stf env variables to be able to override any stf-provider args

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/android-device#44]
Based on the stf provider help there is embedded feature which can read parameters from env:
```
Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_PROVIDER_` (e.g. `STF_PROVIDER_NAME`).
```
i.e. for --public-ip we can just declare `STF_PROVIDER_PUBLIC_IP` env variable and don't provide this value via command line for startup command.

So in scope of the ticket
1. review all stf provider args and provide possibility to override all of them
2. reuse inside internal android-device logic the same variables, for example instead of DEVICENAME reuse everywhere STF_PROVIDER_DEVICE_NAME etc
3. Adjust device2docker script in mcloud-android accordingly

**Comment by vdelendik** [comment]
done. too many changes so regular setup and basic acceptance needed using zebrunner/zebrunner; branch: develop

**Comment by dhreben** [comment]
Verified.
