### ISSUE TITLE
improve SSL setup verification and startup scripts

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/android-device#48]
we have logic which determine if ssl configured as part of the [start_all.sh](https://github.com/zebrunner/android-device/blob/7c24a39d5f5d2f7bbe04a7b2037e49d37c090bb7/files/start_all.sh#L30) scipt

startup scipt should be as simple as possible and websockify cmd line with or without ssl args should be provided by mcloud-android ansible script where SSL configuration happens.

**Comment by vdelendik** [comment]
redesigned approach completely providing protocol and port to be able to determine websocket connection type better.
websockify removed completely and nginx share as well: https://github.com/zebrunner/android-device/pull/63/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R7

acceptance should include MCloud 2.0 setup and manual and automated testing

**Comment by dhreben** [comment]
Verified.
