### ISSUE TITLE
reuse benefits of "wait" bash method to improve healthcheck

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/android-device#50]
from time to time we see that stf cli device service can't be started from 1st attempt:
`Providing all 0 of 1 device(s); ignoring "UDID"`

It was handled by healthchek script but some exit operations just block always recreation.
We have to reorganize start_all.sh to reuse benefits from `wait -n pids` method.

we should wait until processes exists for:
adb
python (websockify)
node (appium, stf provider and cli device)

Note: pay attention that `cli device` service sometimes can't be started from 1st attempt: https://github.com/zebrunner/stf/issues/198

**Comment by vdelendik** [comment]
done.
during the testing pay attention that device which is not started from 1st attempt is marked as unhealthy and should be restarted in 30 sec after start

**Comment by dhreben** [comment]
Verified.
