### ISSUE TITLE
during building image copy stf compiled sources and node packages from stf image

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/android-device#65]
we do stf clone using concrete branch and building again just for android-device repo. it has sense to provide source images and copy all the structure to keep build script for stf in one place.
for example after #64 build process changed in stf and here which is not so good.

**Comment by vdelendik** [comment]
done. significantly speed up build process for current repo providing image asap... during the testing MCloud 2.0 should be deployed and tested as usual.

**Comment by dhreben** [comment]
Verified.
