### ISSUE TITLE
add support for non standard public_ip port and any protocol

### ISSUE THREAD

**Issue by DevsAtSD** [zebrunner/android-device#67]
WS connection with Master node fails since it cannot connect to port configured. Need to update script to add port

**Comment by vdelendik** [comment]
done. to test we have to setup MCloud 2.0 and test using such combinations:
1. 80 and http
2. 443 and https
3. 9090 and http
4. 9443 and https

pay attention to the streaming functionality during manual usage

**Comment by dhreben** [comment]
Verified.

1. 80 and http           - OK
2. 443 and https      - Failed
3. 9090 and http      -OK
4. 9443 and https    - Failed

Relevant ticket with 443 and 9443 ports was opened https://github.com/zebrunner/mcloud-android/issues/74
